apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-seg-streamlit
  labels:
    app: cust-seg-streamlit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cust-seg-streamlit
  template:
    metadata:
      labels:
        app: cust-seg-streamlit
    spec:
      containers:
      - name: cust-seg-streamlit
        image: us-central1-docker.pkg.dev/cust-segment-streamlit-gcp/my-docker-repo/cust-seg-streamlit:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: cust-seg-streamlit-service
spec:
  type: LoadBalancer
  selector:
    app: cust-seg-streamlit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
